### ISSUE TITLE
sentry 注册账号失败

### ISSUE THREAD

**Issue by WebEngineerLi** [woai3c/introduction-to-front-end-engineering#3]
![image](https://user-images.githubusercontent.com/30517805/119366616-bc703380-bce3-11eb-89ba-b395c3d36eff.png)
点击 Create your account 就空白了，请问怎么解决呢
![image](https://user-images.githubusercontent.com/30517805/119366730-d742a800-bce3-11eb-9de4-89a0b8057e81.png)

**Comment by woai3c** [comment]
没有翻墙，网络问题。

**Comment by woai3c** [comment]
太久没响应，关闭问题。
