### ISSUE TITLE
文档中，性能优化段落似乎有个错误，应该是“其它要设为”吧？

### ISSUE THREAD

**Issue by huanganfree** [woai3c/introduction-to-front-end-engineering#7]
![image](https://user-images.githubusercontent.com/41275935/151180466-a3b71aa8-b3bb-409e-bf89-9aeb6418f566.png)

**Comment by woai3c** [comment]
没有，这里讲的就是要将 index.html 设为 no-cache.

**Comment by huanganfree** [comment]
> 没有，这里讲的就是要将 index.html 设为 no-cache.

因为前面是“除了index.html文件”，连起来读感觉怪怪的。:smile:

**Comment by woai3c** [comment]
> > 没有，这里讲的就是要将 index.html 设为 no-cache.
> 
> 因为前面是“除了index.html文件”，连起来读感觉怪怪的。😄

我一会修改下描述。
