### ISSUE TITLE
MiniCssExtractPlugin该插件是提取css到一个文件中的。好像没有压缩功能

### ISSUE THREAD

**Issue by huanganfree** [woai3c/introduction-to-front-end-engineering#8]
![image](https://user-images.githubusercontent.com/41275935/155663047-39f5f5b4-a7dd-4a4a-b154-18ca2d4c22ea.png)

**Comment by woai3c** [comment]
谢谢提醒，已修改 https://github.com/woai3c/introduction-to-front-end-engineering/commit/c162a689d26d5bef4ce99c3d5f53db747c68db99.
